### ISSUE TITLE
Remove react from peer-dependencies?

### ISSUE THREAD

**Issue by DennisSmuda** [hmans/statery#26]
Hello and thanks for your awesome work! 

I am toying witch a "vanilla-typescript" type game and was surprised to see that `statery` installed `react` into my project.

Everything works as expected of course, so no real issues here - just curious if that could be removed? I would be happy to shoot a PR 👍

**Comment by hmans** [comment]
Hey Dennis, thanks for opening this issue. As far as I understand, the main change we'd need to make here is a minor restructuring of the source modules into separate vanilla and react-enabled flavors of the library, plus maybe marking the `react` peer dependency as optional for package managers that support that flag.

If you're willing to make a PR, please go for it! Otherwise I can tackle it the next time I work on this library (but I can't currently make any promises as to when I will find the time.)

**Comment by hmans** [comment]
Since this issue was created, `react` was made a `peerDependency` (which should cause it to not automatically be installed alongside `statery`), and a recent commit explicitly marked it as optional:

```
  "peerDependencies": {
    "react": ">=18.0"
  },
  "peerDependenciesMeta": {
    "react": {
      "optional": true
    }
  }
```

I'm closing this issue for the time being, but please feel free to let me know if this doesn't solve the issue for you.

Since the core of Statery is framework agnostic and there could theoretically be additional framework bindings in the future, it's possible that the project will at some point be split into multiple micropackages, or at least provide separate per-framework entrypoints.
